### ISSUE TITLE
Add option for the user to change 'Refactoring:' prefix

### ISSUE THREAD

**Issue by kristian-jakobsen** [nymann/commit-refactoring#7]

**Comment by nymann** [comment]
I've moved away from having a prefix at all in the beta version. But I still would find this useful.

**Comment by felixthegit** [comment]
I think a prefix would be useful. I use [Arlo's commit notation](https://github.com/RefactoringCombos/ArlosCommitNotation/blob/main/README.md) where small automated commits are prefixed with "r -", meaning it's a refactoring commit (in contrast to a feature commit) and it's a relatively save change.

And in the projects I work for it's common to prefix every commit message with a ticket number which is usually the branch name, too.

Leading to my commit messages usually looking like this:
TICKET-1234: r - Extract method
or
TICKET-1234: F - Sort items by date

(with usually much more "r -" commits than "F" commits so that having them auto filled would be of great help)

Thanks again for you work! ❤️

**Comment by nymann** [comment]
We could use a template configuration for this, where the user can configure it on an application level (not on an individual project level).

In the plugin settings panel we could add a field for a refactoring commit message, that would default to: `${refactoring}`.
And then we could add support for `${branch}`. So in your case you would do `${branch}: r - ${refactoring}`.

Then in the code we resolve the template variables. What do you think @felixthegit ?

**Comment by felixthegit** [comment]
That sounds pretty perfect to me

**Comment by nymann** [comment]
I implemented it @felixthegit it's released in the 0.1.5-beta release, you can download the zip file from the [marketplace](https://plugins.jetbrains.com/plugin/25085-commit-refactoring/edit/versions/beta/590135) or from the [release](https://github.com/nymann/commit-refactoring/releases/tag/v0.1.5-beta) let me know what you think or if you experience any issues.

Before I release it I would like to add a better description to the new Settings window

**Comment by nymann** [comment]
![image](https://github.com/user-attachments/assets/eba85727-5d25-4d03-9964-231450e1437a)

**Comment by felixthegit** [comment]
Works like a charm :)

**Comment by nymann** [comment]
Great, It's pending release in the main version, should be approved by JetBrains at the end of the day 👍
